database_cfg: "/home/nmehlman/disney/AMI-diarization-setup/pyannote/database.yml"
protocol: 'AMI.SpeakerDiarization.only_words'

task:
  batch_size: 64

model:
  sample_rate: 16000
  attention_heads_cc: 4
  attention_heads_cf: 4
  use_pretrained_weights: true
  freeze_encoders: true
  lr: 0.001

trainer:
  max_epochs: 100
  devices: 1
  accelerator: "gpu"
  val_check_interval: 50
  gradient_clip_val: 0.001
  log_every_n_steps: 50
  #overfit_batches: 32

tensorboard:
  save_dir: "/home/nmehlman/logs/pyannote_mc"
  name: "test"
  version: 0     # Automatic versioning if set to null (recommended)
