database_cfg: "/home/nmehlman/disney/AMI-diarization-setup/pyannote/database.yml"
protocol: 'AMI.SpeakerDiarization.only_words'

task:
  batch_size: 32

model:
  sample_rate: 16000
  attention_heads_cc: 4
  attention_heads_cf: 4
  use_pretrained_weights: true
  freeze_encoders: true

trainer:
  max_epochs: 50
  devices: 1
  accelerator: "gpu"
  val_check_interval: 100
  gradient_clip_val: 0.5
  log_every_n_steps: 10

tensorboard:
  save_dir: "/home/nmehlman/logs/pyannote_mc"
  name: "test"
  version: 1     # Automatic versioning if set to null (recommended)
