model: 'vad_fusion'

use_oracle: false

model_kwargs:
  vad_weight: 0.5
  device: 'cuda:0'

dataset: 'ami_multichannel'

dataset_kwargs:
  array_root_path: '/proj/disney/amicorpus_array'
  lav_root_path: '/proj/disney/amicorpus_lav'
  sample_len_s: 15.0
  min_speaker_gap_s: 1.0 

diarize_kwargs:
  sample_rate: 16000

save_dir: "/home/nmehlman/disney/multiparty_diarization/results/ami_vad_fusion/"
